# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query_qes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='\u6d4b\u8bc4\u540d\u79f0')),
                ('count', models.IntegerField(default=0, verbose_name='\u9898\u76ee\u6570\u91cf')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='\u9898\u76ee\u540d\u79f0')),
                ('item_1', models.TextField(verbose_name='\u6761\u76ee\u4e00')),
                ('item_2', models.TextField(verbose_name='\u6761\u76ee\u4e8c')),
                ('item_1_score', models.IntegerField(max_length=8, verbose_name='\u5f97\u52061')),
                ('item_2_score', models.IntegerField(max_length=8, verbose_name='\u5f97\u52062')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Query_qes', verbose_name='\u6240\u5c5e\u9898\u5e93')),
            ],
        ),
    ]
