# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-12 03:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultSimple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_1', models.IntegerField(verbose_name='\u5206\u5272\u7ebf1')),
                ('lever_2', models.IntegerField(verbose_name='\u5206\u5272\u7ebf2')),
                ('content_1', models.TextField(verbose_name='\u7b2c\u4e00\u7ea7\u7ed3\u679c')),
                ('content_2', models.TextField(verbose_name='\u7b2c\u4e8c\u7ea7\u7ed3\u679c')),
                ('content_3', models.TextField(verbose_name='\u7b2c\u4e09\u7ea7\u7ed3\u679c')),
                ('belong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.Query_qes', verbose_name='\u6240\u5c5e\u9898\u5e93')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='item_1_score',
            field=models.IntegerField(verbose_name='\u5f97\u52061'),
        ),
        migrations.AlterField(
            model_name='question',
            name='item_2_score',
            field=models.IntegerField(verbose_name='\u5f97\u52062'),
        ),
    ]
