# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 10:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_auto_20190312_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultsimple',
            old_name='lever_2',
            new_name='level_2',
        ),
    ]
