# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=1, verbose_name='\u7528\u6237\u7c7b\u578b'),
        ),
    ]
