# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-13 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u7528\u6237\u540d')),
                ('password', models.CharField(max_length=32, verbose_name='\u5bc6\u7801')),
                ('role', models.IntegerField(choices=[(0, '\u7ba1\u7406\u5458'), (1, '\u7528\u6237')], default=1, verbose_name='\u7528\u6237\u7c7b\u578b')),
            ],
        ),
    ]
